# Generated by Django 4.1.1 on 2022-10-28 17:33

import apps.images.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Image Name')),
                ('image', models.ImageField(upload_to=apps.images.models.imageset_upload_images_path)),
                ('is_inferenced', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='eg. flowers', max_length=100)),
                ('description', models.TextField()),
                ('dirpath', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='imageset',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_imageset_by_user'),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='image_set',
            field=models.ForeignKey(help_text='Image Set of the uploading images', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='images.imageset'),
        ),
    ]
