# Generated by Django 4.1.1 on 2022-11-05 05:25

import apps.videos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Image Name')),
                ('video', models.FileField(upload_to=apps.videos.models.videoset_upload_images_path)),
                ('is_inferenced', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='eg. flowers', max_length=100)),
                ('description', models.TextField()),
                ('dirpath', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='videoset',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_videoset_by_user'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='video_set',
            field=models.ForeignKey(help_text='Video Set of the uploading images', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.videoset'),
        ),
    ]
