# Generated by Django 4.1.1 on 2022-11-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        ('detect', '0002_alter_inferencedimage_yolo_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferencedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inf_video_path', models.CharField(blank=True, max_length=250, null=True)),
                ('detection_info', models.JSONField(blank=True, null=True)),
                ('yolo_model', models.CharField(blank=True, choices=[('yolov5s.pt', 'yolov5s.pt'), ('yolov5m.pt', 'yolov5m.pt'), ('yolov5l.pt', 'yolov5l.pt'), ('yolov5x.pt', 'yolov5x.pt'), ('best.pt', 'best.pt')], default=('yolov5s.pt', 'yolov5s.pt'), help_text='Selected yolo model will download.                                  Requires an active internet connection.', max_length=250, null=True, verbose_name='YOLOV5 Models')),
                ('model_conf', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Model confidence')),
                ('orig_video', models.ForeignKey(blank=True, help_text='Main Video', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detectedvideos', to='videos.videofile')),
            ],
        ),
    ]
